dist: xenial
language: go
go:
  - "1.13.x"
cache:
  directories:
    - $GOPATH/pkg/mod
go_import_path: github.com/ykhr53/bmo
branches:
  only:
  - master
env:
  global:
    - SLACKTOKEN=xoxb-forbar
    - VTOKEN=vtoken-forbar
    - BOTUNAME=UBOTNAMEFOOBAR
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
